project:
  type: website
  title: "Computing Basics and Intro to R"
  execute-dir: project
  output-dir: docs
  render:
      - index.qmd
#      - about.qmd
      - lessons/shell-intro/shell-intro.qmd
      - lessons/github/github-intro.qmd
      - lessons/github/exercise1.qmd
      - lessons/github/exercise2.qmd
      - lessons/github/exercise3.qmd
      - lessons/github/ssh_setup.qmd
      - lessons/r-lessons/r-intro.qmd
      - lessons/r-lessons/r-plotting.qmd
      - lessons/r-lessons/r-tidydata.qmd
      - lessons/r-lessons/r-markdown.qmd
website:
  title: "Computing Basics and Intro to R"
  site-url: https://SyracuseUniversity.github.io/ospo-workshop-r-intro
  repo-url: https://https://github.com/SyracuseUniversity/ospo-workshop-r-intro
  repo-actions: [issue]
  back-to-top-navigation: true
  page-footer:
    border: true
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2024, [Syracuse University Open Source Program Office](https://opensource.syracuse.edu/)"
    background: "#F76900"
    foreground: "#000E54"
  sidebar:
    style: "docked"
    search: true
    foreground: "#000E54"
    background: "#F76900"
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://https://github.com/SyracuseUniversity/ospo-workshop-r-intro
          - text: Report a Bug
            href: https://https//github.com/SyracuseUniversity/ospo-workshop-r-intro/issues/new
    collapse-level: 1
    contents:
      - lessons/shell-intro/shell-intro.qmd
      - section: "<code>git</code> and GitHub"
        href: lessons/github/github-intro.qmd
        contents:
          - lessons/github/exercise1.qmd
          - lessons/github/exercise2.qmd
          - lessons/github/exercise3.qmd
      - lessons/r-lessons/r-intro.qmd
      - lessons/r-lessons/r-plotting.qmd
      - lessons/r-lessons/r-tidydata.qmd
      - lessons/r-lessons/r-markdown.qmd
  page-navigation: true

execute:
  freeze: auto

format:
  html:
    theme: lumen
    css: styles.css
    toc: true

callout-appearance: default

date: today
date-format: iso
